# Generated by Django 4.2.7 on 2023-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibraray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book_instance',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
