# Generated by Django 4.2.7 on 2023-12-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibraray', '0002_alter_author_dob_alter_book_instance_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_instance',
            name='dueDate',
            field=models.DateField(null=True),
        ),
    ]
