# Generated by Django 4.2.7 on 2023-12-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibraray', '0004_alter_book_instance_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_instance',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
