# Generated by Django 4.2.7 on 2023-12-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibraray', '0005_alter_book_instance_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_instance',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
